// Employees Part 2 (2 of 2) — Jaipur Branch — 172 employees
module.exports = [
  { empCode: '1800144', name: 'NARBADA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Narbada_44' },
  { empCode: '1802075', name: 'NARENDRA KUMAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Narendra_75' },
  { empCode: '1800040', name: 'NARESH BANSAL', department: 'Procurement', designation: 'Officer', role: 'EMPLOYEE', password: 'Naresh_40' },
  { empCode: '1800168', name: 'NATHI DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Nathi_68' },
  { empCode: '1802040', name: 'NATHU', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Nathu_40' },
  { empCode: '1802288', name: 'NEPAL SINGH SONDIYA', department: 'Production', designation: 'Helper - Production', role: 'EMPLOYEE', password: 'Nepal_88' },
  { empCode: '1802387', name: 'NIKITA MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Nikita_87' },
  { empCode: '1802145', name: 'NITU YOGI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Nitu_45' },
  { empCode: '1800031', name: 'OM PRAKASH SHARMA', department: 'Distribution', designation: 'Supervisor', role: 'SUPERVISOR', password: 'Om_31' },
  { empCode: '1801862', name: 'OMPRAKASH', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Omprakash_62' },
  { empCode: '1801236', name: 'OMPRAKSH GURJAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ompraksh_36' },
  { empCode: '1801716', name: 'PANKAJ BHARDWAJ', department: 'Human Resources', designation: 'Senior Executive', role: 'EMPLOYEE', password: 'Pankaj_16' },
  { empCode: '1801079', name: 'Pappu Lal', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Pappu_79' },
  { empCode: '1800557', name: 'PARMESHWAR MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Parmeshwar_57' },
  { empCode: '1801187', name: 'Pinki Jain', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Pinki_87' },
  { empCode: '1802372', name: 'PINTU MEENA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Pintu_72' },
  { empCode: '1801122', name: 'Pooran Mal Meena', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Pooran_22' },
  { empCode: '1801237', name: 'PRABHU NARAYAN MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Prabhu_37' },
  { empCode: '1800060', name: 'PRADHAN GURJAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Pradhan_60' },
  { empCode: '1801238', name: 'PRAKASH CHAND MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Prakash_38' },
  { empCode: '1800010', name: 'PRAKASH CHAND VIJAY', department: 'Finance', designation: 'Deputy General Manager', role: 'EMPLOYEE', password: 'Prakash_10' },
  { empCode: '1802366', name: 'Pramod Kumar Sharma', department: 'Finance', designation: 'Assistant Manager', role: 'EMPLOYEE', password: 'Pramod_66' },
  { empCode: '1800544', name: 'PRAVEEN SHARMA', department: 'Distribution', designation: 'Supervisor', role: 'SUPERVISOR', password: 'Praveen_44' },
  { empCode: '1800979', name: 'PREM DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Prem_79' },
  { empCode: '1800134', name: 'PREM DEVI REGAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Prem_34' },
  { empCode: '1801748', name: 'PREMLATA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Premlata_48' },
  { empCode: '1802188', name: 'PUKHRAJ JWALA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Pukhraj_88' },
  { empCode: '1801961', name: 'PURANMAL', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Puranmal_61' },
  { empCode: '1802328', name: 'PUSHPENDRA MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Pushpendra_28' },
  { empCode: '1801791', name: 'PUSHPENDRA YADAV', department: 'Distribution', designation: 'Supervisor', role: 'SUPERVISOR', password: 'Pushpendra_91' },
  { empCode: '1800135', name: 'RADHA DEVI BALAI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Radha_35' },
  { empCode: '1800160', name: 'RADHA SHARMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Radha_60' },
  { empCode: '1801240', name: 'RADHESHYAM', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Radheshyam_40' },
  { empCode: '1801362', name: 'Rahul Singh CHAUHAN', department: 'Distribution', designation: 'Supervisor - Distribution', role: 'SUPERVISOR', password: 'Rahul_62' },
  { empCode: '1800110', name: 'RAJANTI DEVI MORYA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rajanti_10' },
  { empCode: '1801241', name: 'RAJENDRA JAJORIYA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rajendra_41' },
  { empCode: '1801840', name: 'RAJENDRA KUMAR MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rajendra_40' },
  { empCode: '1801242', name: 'RAJENDRA LAKHERA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rajendra_42' },
  { empCode: '1802324', name: 'RAJENDRA PRASAD MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rajendra_24' },
  { empCode: '1800003', name: 'Rajesh Kaushik', department: 'Human Resources', designation: 'AGM - Human Resources', role: 'EMPLOYEE', password: 'Rajesh_03' },
  { empCode: '1801305', name: 'RAJESH KUMAR MEENA', department: 'Distribution', designation: 'Executive', role: 'EMPLOYEE', password: 'Rajesh_05' },
  { empCode: '1800012', name: 'Rajesh Kumar Sharma', department: 'Procurement', designation: 'Assistant General Manager', role: 'EMPLOYEE', password: 'Rajesh_12' },
  { empCode: '1802384', name: 'RAJU DAS VAISHNAV', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Raju_84' },
  { empCode: '1801243', name: 'RAJU LAL', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Raju_43' },
  { empCode: '1801316', name: 'Raju Meena', department: 'Production', designation: 'Supervisor', role: 'SUPERVISOR', password: 'Raju_16' },
  { empCode: '1801767', name: 'RAJU TANWAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Raju_67' },
  { empCode: '1802351', name: 'RAJU VERMA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Raju_51' },
  { empCode: '1802331', name: 'RAKESH KUMAR BUNKAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rakesh_31' },
  { empCode: '1800252', name: 'RAKESH KUMAR MEENA', department: 'Distribution', designation: 'Supervisor', role: 'SUPERVISOR', password: 'Rakesh_52' },
  { empCode: '1801288', name: 'RAKESH KUMAR MEENA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Rakesh_88' },
  { empCode: '1800095', name: 'RAKESH VIJAY', department: 'Procurement', designation: 'Officer', role: 'EMPLOYEE', password: 'Rakesh_95' },
  { empCode: '1801246', name: 'RAM DAYAL SHARMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ram_46' },
  { empCode: '1801248', name: 'RAMAVATAR MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ramavatar_48' },
  { empCode: '1801754', name: 'RAMAVTAR', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Ramavtar_54' },
  { empCode: '1801078', name: 'Rambati Devi', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rambati_78' },
  { empCode: '1802183', name: 'RAMESH CHAND', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Ramesh_83' },
  { empCode: '1800274', name: 'RAMESH CHAND SHARMA', department: 'Distribution', designation: 'Supervisor', role: 'SUPERVISOR', password: 'Ramesh_74' },
  { empCode: '1801391', name: 'Ramesh Kumar Mali', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ramesh_91' },
  { empCode: '1801912', name: 'RAMESHCHAND', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rameshchand_12' },
  { empCode: '1802230', name: 'RAMESHWAR DAYAL', department: 'Human Resources', designation: 'Executive', role: 'EMPLOYEE', password: 'Rameshwar_30' },
  { empCode: '1802353', name: 'RAMESHWAR SAINI', department: 'Stores', designation: 'Executive', role: 'EMPLOYEE', password: 'Rameshwar_53' },
  { empCode: '1801463', name: 'RAMNIWAS CHOUDHARY', department: 'Quality', designation: 'Officer - Quality', role: 'EMPLOYEE', password: 'Ramniwas_63' },
  { empCode: '1802049', name: 'RAMOTAR RANA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ramotar_49' },
  { empCode: '1802059', name: 'RAMPRASAD MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ramprasad_59' },
  { empCode: '1801607', name: 'RAMRAJ MEENA', department: 'Production', designation: 'COOK', role: 'EMPLOYEE', password: 'Ramraj_07' },
  { empCode: '1801591', name: 'RANJIT YOGI', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Ranjit_91' },
  { empCode: '1800050', name: 'RATAN LAL DARJI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ratan_50' },
  { empCode: '1801883', name: 'RATAN LAL MEENA', department: 'Production', designation: 'Supervisor', role: 'SUPERVISOR', password: 'Ratan_83' },
  { empCode: '1801642', name: 'RATAN SINGH', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ratan_42' },
  { empCode: '1800120', name: 'RATNA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ratna_20' },
  { empCode: '1802115', name: 'RAVI THAKUR', department: 'Finance', designation: 'Executive', role: 'EMPLOYEE', password: 'Ravi_15' },
  { empCode: '1802371', name: 'RAVINDRA KUMAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ravindra_71' },
  { empCode: '1802289', name: 'RAVINDRA KUMAR MEENA', department: 'Production', designation: 'Helper - Production', role: 'EMPLOYEE', password: 'Ravindra_89' },
  { empCode: '1801664', name: 'RAVINDRA SHARMA', department: 'Distribution', designation: 'Supervisor', role: 'SUPERVISOR', password: 'Ravindra_64' },
  { empCode: '1802264', name: 'REENA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Reena_64' },
  { empCode: '1800153', name: 'REETA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Reeta_53' },
  { empCode: '1802147', name: 'REKHA RAWAT', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rekha_47' },
  { empCode: '1801735', name: 'REWAT SINGH', department: 'Production', designation: 'Operator', role: 'EMPLOYEE', password: 'Rewat_35' },
  { empCode: '1801952', name: 'RINKU CHOPRA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rinku_52' },
  { empCode: '1802244', name: 'RINKU MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rinku_44' },
  { empCode: '1802024', name: 'RINKU MORYA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Rinku_24' },
  { empCode: '1800349', name: 'RISHPAL KUMAWAT', department: 'Information Technology', designation: 'Assistant Manager', role: 'ADMIN', password: 'Rishpal_49' },
  { empCode: '1800082', name: 'RODU RAM MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rodu_82' },
  { empCode: '1802363', name: 'ROHAN KUMAR CHOPRA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Rohan_63' },
  { empCode: '1802009', name: 'ROHITASH KUMAR REDDY', department: 'Production', designation: 'Helper-Production', role: 'EMPLOYEE', password: 'Rohitash_09' },
  { empCode: '1801252', name: 'ROOPNARAYAN MOURYA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Roopnarayan_52' },
  { empCode: '1801291', name: 'ROSHAN LAL', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Roshan_91' },
  { empCode: '1801481', name: 'Roshan Sharma', department: 'Maintenance', designation: 'Fitter', role: 'EMPLOYEE', password: 'Roshan_81' },
  { empCode: '1802152', name: 'SACHIN RAISWAL', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sachin_52' },
  { empCode: '1802386', name: 'SAGAR MAL GOME', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Sagar_86' },
  { empCode: '1802355', name: 'SAHIL TANVAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sahil_55' },
  { empCode: '1802073', name: 'SAMAY SINGH', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Samay_73' },
  { empCode: '1802304', name: 'SANDEEP SAINI', department: 'Quality', designation: 'Executive', role: 'EMPLOYEE', password: 'Sandeep_04' },
  { empCode: '1801253', name: 'SANJAY', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sanjay_53' },
  { empCode: '1802332', name: 'SANJAY KUMAR SAINI', department: 'Process Excellence and CI', designation: 'Officer', role: 'EMPLOYEE', password: 'Sanjay_32' },
  { empCode: '1801378', name: 'Sanjay Sharma', department: 'Distribution', designation: 'Supervisor - Distribution', role: 'SUPERVISOR', password: 'Sanjay_78' },
  { empCode: '1802343', name: 'SANJAY SHARMA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Sanjay_43' },
  { empCode: '1800011', name: 'SANT KUMAR SHARMA', department: 'Operations', designation: 'Manager', role: 'BRANCH_MANAGER', password: 'Sant_11' },
  { empCode: '1801347', name: 'Santosh Devi', department: 'Stores', designation: 'Helper', role: 'EMPLOYEE', password: 'Santosh_47' },
  { empCode: '1801544', name: 'SANTOSH DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Santosh_44' },
  { empCode: '1802056', name: 'SANTOSH KUMAR', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Santosh_56' },
  { empCode: '1802141', name: 'SANTRA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Santra_41' },
  { empCode: '1800137', name: 'SANTRA DEVI MAHAWAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Santra_37' },
  { empCode: '1800112', name: 'SANTRA DEVI REIGER', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Santra_12' },
  { empCode: '1801747', name: 'SANTRA PRAJAPAT', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Santra_47' },
  { empCode: '1802143', name: 'SARVAGYA KUMAR SHARMA', department: 'Distribution', designation: 'Executive', role: 'EMPLOYEE', password: 'Sarvagya_43' },
  { empCode: '1802240', name: 'SATISH TIWARI', department: 'Production', designation: 'Operator', role: 'EMPLOYEE', password: 'Satish_40' },
  { empCode: '1801254', name: 'SATYA NARAYAN', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Satya_54' },
  { empCode: '1802233', name: 'SAVITA BALAI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Savita_33' },
  { empCode: '1802099', name: 'SAVITA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Savita_99' },
  { empCode: '1801293', name: 'SAYAR LAL SHARMA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Sayar_93' },
  { empCode: '1802090', name: 'SEEMA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Seema_90' },
  { empCode: '1802377', name: 'SEEMA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Seema_77' },
  { empCode: '1801878', name: 'SEEMA KANWAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Seema_78' },
  { empCode: '1800496', name: 'SEETA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Seeta_96' },
  { empCode: '1800113', name: 'SHAKUNTLA DEVI SHARMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Shakuntla_13' },
  { empCode: '1802119', name: 'SHANKAR LAL MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Shankar_19' },
  { empCode: '1801873', name: 'SHANKAR SINGH', department: 'Production', designation: 'Operator', role: 'EMPLOYEE', password: 'Shankar_73' },
  { empCode: '1801888', name: 'SHANKARA NAND', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Shankara_88' },
  { empCode: '1800115', name: 'SHANTI DEVI MORYA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Shanti_15' },
  { empCode: '1801846', name: 'SHASHI DEVI SHARMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Shashi_46' },
  { empCode: '1802339', name: 'SHEKHAR BAIRWA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Shekhar_39' },
  { empCode: '1802269', name: 'SHIMLA SHARMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Shimla_69' },
  { empCode: '1802375', name: 'SHIVKESH MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Shivkesh_75' },
  { empCode: '1801053', name: 'Shivraj Gurjar', department: 'Production', designation: 'COOK', role: 'EMPLOYEE', password: 'Shivraj_53' },
  { empCode: '1801671', name: 'SHRI NARAYAN BAIRWA', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Shri_71' },
  { empCode: '1802021', name: 'SHYAMSUNDAR BHAT', department: 'Maintenance', designation: 'Operator', role: 'EMPLOYEE', password: 'Shyamsundar_21' },
  { empCode: '1802057', name: 'SHYOJI LAL MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Shyoji_57' },
  { empCode: '1802176', name: 'SOHAN LAL', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Sohan_76' },
  { empCode: '1802118', name: 'SONIYA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Soniya_18' },
  { empCode: '1801780', name: 'SONU', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sonu_80' },
  { empCode: '1802360', name: 'SONU', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sonu_60' },
  { empCode: '1801892', name: 'SONU BUNKER', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sonu_92' },
  { empCode: '1802025', name: 'SONU DHANAKA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sonu_25' },
  { empCode: '1802362', name: 'SONU JATAV', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Sonu_62' },
  { empCode: '1802338', name: 'SONU KUMAR MEENA', department: 'Stores', designation: 'Helper', role: 'EMPLOYEE', password: 'Sonu_38' },
  { empCode: '1800006', name: 'SUBHASH CHAND GAUR', department: 'Stores', designation: 'Deputy Manager', role: 'EMPLOYEE', password: 'Subhash_06' },
  { empCode: '1800978', name: 'SUKHIYA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sukhiya_78' },
  { empCode: '1801534', name: 'SUKHRAM', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sukhram_34' },
  { empCode: '1801170', name: 'Sumit Sharma', department: 'Finance', designation: 'Executive', role: 'EMPLOYEE', password: 'Sumit_70' },
  { empCode: '1800154', name: 'SUMITRA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sumitra_54' },
  { empCode: '1800181', name: 'SUNIL AGARWAL', department: 'Maintenance', designation: 'Electrician', role: 'EMPLOYEE', password: 'Sunil_81' },
  { empCode: '1801656', name: 'SUNIL KUMAR MOURYA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sunil_56' },
  { empCode: '1801947', name: 'SUNIL MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sunil_47' },
  { empCode: '1802365', name: 'SUNIL MEGHWAL', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sunil_65' },
  { empCode: '1801924', name: 'SUNITA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sunita_24' },
  { empCode: '1800117', name: 'SUNITA DEVI MORYA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sunita_17' },
  { empCode: '1802069', name: 'SUNNY MAURYA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sunny_69' },
  { empCode: '1801366', name: 'Suraj Mal Gurjar', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Suraj_66' },
  { empCode: '1801728', name: 'SURENDER SINGH', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Surender_28' },
  { empCode: '1802352', name: 'SURESH VERMA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Suresh_52' },
  { empCode: '1801768', name: 'SURGYAN', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Surgyan_68' },
  { empCode: '1800361', name: 'SUSHEEL KUMAR MAHAWAR', department: 'Distribution', designation: 'Officer', role: 'EMPLOYEE', password: 'Susheel_61' },
  { empCode: '1801746', name: 'SUSHILA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sushila_46' },
  { empCode: '1801025', name: 'SUSHILA PRAJAPAT', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Sushila_25' },
  { empCode: '1800046', name: 'SYOJI RAM JAT', department: 'Production', designation: 'Supervisor', role: 'SUPERVISOR', password: 'Syoji_46' },
  { empCode: '1802383', name: 'TARACHAND BHEEL', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Tarachand_83' },
  { empCode: '1802250', name: 'TEJA RAM GURJAR', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Teja_50' },
  { empCode: '1801259', name: 'TUFAN MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Tufan_59' },
  { empCode: '1800143', name: 'UGANTI DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Uganti_43' },
  { empCode: '1802254', name: 'UMESH', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Umesh_54' },
  { empCode: '1801298', name: 'UMMED SINGH', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Ummed_98' },
  { empCode: '1801598', name: 'VEDPRAKASH MEENA', department: 'Distribution', designation: 'Supervisor', role: 'SUPERVISOR', password: 'Vedprakash_98' },
  { empCode: '1802287', name: 'VIJAY PAL MEENA', department: 'Production', designation: 'Helper - Production', role: 'EMPLOYEE', password: 'Vijay_87' },
  { empCode: '1801759', name: 'VIJAY SHANKAR MEENA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Vijay_59' },
  { empCode: '1801427', name: 'Vijay Vikram Singh', department: 'Production', designation: 'Operator', role: 'EMPLOYEE', password: 'Vijay_27' },
  { empCode: '1802345', name: 'VIKAS KUMAR MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Vikas_45' },
  { empCode: '1801938', name: 'VIKAS MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Vikas_38' },
  { empCode: '1802347', name: 'VIKASH SINGH', department: 'Maintenance', designation: 'Operator', role: 'EMPLOYEE', password: 'Vikash_47' },
  { empCode: '1800079', name: 'VIMAL PRAKASH SHARMA', department: 'Finance', designation: 'Senior Executive', role: 'EMPLOYEE', password: 'Vimal_79' },
  { empCode: '1801545', name: 'VIMALA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Vimala_45' },
  { empCode: '1801853', name: 'VINOD KUMAR MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Vinod_53' },
  { empCode: '1801260', name: 'VINOD RAIGAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Vinod_60' },
  { empCode: '1800474', name: 'VIRENDRA KUMAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Virendra_74' },
  { empCode: '1802283', name: 'VISHAL SHARMA', department: 'Distribution', designation: 'Assistant Supervisor', role: 'SUPERVISOR', password: 'Vishal_83' },
  { empCode: '1802359', name: 'VISHANU YOGI', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Vishanu_59' },
  { empCode: '1801299', name: 'YADRAM MEENA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Yadram_99' },
  { empCode: '1802281', name: 'YADRAM MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Yadram_81' },
  { empCode: '1802369', name: 'YASHPAL JATAV', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Yashpal_69' },
  { empCode: '1801442', name: 'Yogesh Dadhich', department: 'Finance', designation: 'Senior Executive - Accounts', role: 'EMPLOYEE', password: 'Yogesh_42' },
];
