// Employees Part 1 (1 of 2) — Jaipur Branch — 173 employees
module.exports = [
  { empCode: '1801157', name: 'Aashish Arora', department: 'Procurement', designation: 'Officer', role: 'EMPLOYEE', password: 'Aashish_57' },
  { empCode: '1801958', name: 'AJAY DHANKA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Ajay_58' },
  { empCode: '1802316', name: 'AJAY KUMAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ajay_16' },
  { empCode: '1802342', name: 'AJAY KUMAR RAIGAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ajay_42' },
  { empCode: '1800022', name: 'AMIT KESHWA', department: 'Operations', designation: 'General Manager', role: 'CLUSTER_MANAGER', password: 'Amit_22' },
  { empCode: '1001048', name: 'ANAMIKA SHARMA', department: 'India One Marketing', designation: 'Deputy Manager', role: 'EMPLOYEE', password: 'Anamika_48' },
  { empCode: '1801541', name: 'ANIL KUMAR SINDHI', department: 'Finance', designation: 'Deputy Manager', role: 'EMPLOYEE', password: 'Anil_41' },
  { empCode: '1802037', name: 'ANITA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Anita_37' },
  { empCode: '1802132', name: 'ANITA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Anita_32' },
  { empCode: '1802327', name: 'ANITA VERMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Anita_27' },
  { empCode: '1801793', name: 'ANJANI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Anjani_93' },
  { empCode: '1802259', name: 'ANKIT SAINI', department: 'Stores', designation: 'Executive', role: 'EMPLOYEE', password: 'Ankit_59' },
  { empCode: '1802382', name: 'ANKUSH POTTER', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Ankush_82' },
  { empCode: '2000448', name: 'ANSAR HUSAIN', department: 'Maintenance', designation: 'Electrician', role: 'EMPLOYEE', password: 'Ansar_48' },
  { empCode: '1801994', name: 'ARJUN LAL MAHAWAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Arjun_94' },
  { empCode: '1801990', name: 'ARTI DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Arti_90' },
  { empCode: '1801920', name: 'ASHOK', department: 'Maintenance', designation: 'Welder - Maintenance', role: 'EMPLOYEE', password: 'Ashok_20' },
  { empCode: '1801264', name: 'ASHOK KUMAR DHANKA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Ashok_64' },
  { empCode: '1800346', name: 'ASHOK KUMAR YADAV', department: 'Distribution', designation: 'Officer', role: 'EMPLOYEE', password: 'Ashok_46' },
  { empCode: '1802010', name: 'ASHOK KUMAR YADAV', department: 'Distribution', designation: 'Supervisor - Distribution', role: 'SUPERVISOR', password: 'Ashok_10' },
  { empCode: '1802113', name: 'ASHOK YOGI', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Ashok_13' },
  { empCode: '1802380', name: 'AVINASH', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Avinash_80' },
  { empCode: '1801869', name: 'BABALI DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Babali_69' },
  { empCode: '1801822', name: 'BABLU SHARMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Bablu_22' },
  { empCode: '1801265', name: 'BABU LAL GURJAR', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Babu_65' },
  { empCode: '1801637', name: 'BABU LAL MEENA', department: 'Distribution', designation: 'Executive', role: 'EMPLOYEE', password: 'Babu_37' },
  { empCode: '1800128', name: 'BABURI DEVI MORYA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Baburi_28' },
  { empCode: '1801205', name: 'BAJRANG SINGH', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Bajrang_05' },
  { empCode: '1802306', name: 'BALVEER SINGH', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Balveer_06' },
  { empCode: '1801206', name: 'BALWEER SINGH', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Balweer_06' },
  { empCode: '1800104', name: 'BARDI DEVI PRAJPAT', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Bardi_04' },
  { empCode: '1801208', name: 'BHAGWAN SHAY BAIRWA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Bhagwan_08' },
  { empCode: '1801765', name: 'BHAGWATI DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Bhagwati_65' },
  { empCode: '1801445', name: 'Bharat Bhushan Arora', department: 'Administration', designation: 'Executive', role: 'EMPLOYEE', password: 'Bharat_45' },
  { empCode: '1801726', name: 'BHARAT KUMAR YADAV', department: 'Information Technology', designation: 'Executive', role: 'EMPLOYEE', password: 'Bharat_26' },
  { empCode: '1802215', name: 'BHAWANI SINGH', department: 'Quality', designation: 'Regional Manager', role: 'EMPLOYEE', password: 'Bhawani_15' },
  { empCode: '1800463', name: 'BHOJRAJ SINGH', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Bhojraj_63' },
  { empCode: '1801131', name: 'Bhupendra Singh Rathore', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Bhupendra_31' },
  { empCode: '1802348', name: 'BHUROBAI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Bhurobai_48' },
  { empCode: '1801267', name: 'BIJENDRA SHARMA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Bijendra_67' },
  { empCode: '1802286', name: 'CHANDAN SINGH', department: 'Production', designation: 'Helper - Production', role: 'EMPLOYEE', password: 'Chandan_86' },
  { empCode: '1800996', name: 'CHANDESHWAR THAKUR', department: 'Production', designation: 'Operator', role: 'EMPLOYEE', password: 'Chandeshwar_96' },
  { empCode: '1802330', name: 'CHANDRASHEKHAR', department: 'Distribution', designation: 'Supervisor', role: 'SUPERVISOR', password: 'Chandrashekhar_30' },
  { empCode: '1802045', name: 'CHARAT KUMAR DHOBI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Charat_45' },
  { empCode: '5100029', name: 'CHETAN SINGH BHATI', department: 'Human Resources', designation: 'Senior Executive - HR', role: 'EMPLOYEE', password: 'Chetan_29' },
  { empCode: '1802130', name: 'CHHOTI DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Chhoti_30' },
  { empCode: '1802129', name: 'CHHOTURAM GUJAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Chhoturam_29' },
  { empCode: '1800122', name: 'CHOTA DEVI REGAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Chota_22' },
  { empCode: '1801155', name: 'Dashrath kumar', department: 'Production', designation: 'Assistant Manager', role: 'EMPLOYEE', password: 'Dashrath_55' },
  { empCode: '1802087', name: 'DASHRATH SINGH YADAV', department: 'Production', designation: 'Assistant Supervisor', role: 'SUPERVISOR', password: 'Dashrath_87' },
  { empCode: '1801270', name: 'DAYA CHAND VERMA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Daya_70' },
  { empCode: '1800314', name: 'DAYARAM RAM GURJAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Dayaram_14' },
  { empCode: '1802376', name: 'DEEPAK MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Deepak_76' },
  { empCode: '1802053', name: 'DEEPAK MUNDOTIA', department: 'Human Resources', designation: 'Executive', role: 'EMPLOYEE', password: 'Deepak_53' },
  { empCode: '1801827', name: 'DEEPAK SAINI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Deepak_27' },
  { empCode: '1802078', name: 'DESH VANDHU', department: 'Production', designation: 'Assistant Supervisor', role: 'SUPERVISOR', password: 'Desh_78' },
  { empCode: '1802379', name: 'DHANRAJ BHEEL', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Dhanraj_79' },
  { empCode: '1800390', name: 'DHANRAJ JAT', department: 'Production', designation: 'COOK', role: 'EMPLOYEE', password: 'Dhanraj_90' },
  { empCode: '1800086', name: 'DHARAM RAJ SAINI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Dharam_86' },
  { empCode: '1801271', name: 'DHARMENDRA KUMAR', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Dharmendra_71' },
  { empCode: '1801654', name: 'Dheeraj Yadav', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Dheeraj_54' },
  { empCode: '1802357', name: 'DILIP KUMAR MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Dilip_57' },
  { empCode: '1801772', name: 'DILIP KUMAR PANDA', department: 'Maintenance', designation: 'Officer', role: 'EMPLOYEE', password: 'Dilip_72' },
  { empCode: '1801272', name: 'DINESH KUMAR BALAI', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Dinesh_72' },
  { empCode: '1800487', name: 'DINESH KUMAR MALI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Dinesh_87' },
  { empCode: '1802238', name: 'GAJANAND BAIRWA', department: 'Maintenance', designation: 'Plumber', role: 'EMPLOYEE', password: 'Gajanand_38' },
  { empCode: '1802373', name: 'GAJANAND CHOUDHARY', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Gajanand_73' },
  { empCode: '1801273', name: 'GAJANAND RAIGAR', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Gajanand_73' },
  { empCode: '1802241', name: 'GANESH NARAYAN MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Ganesh_41' },
  { empCode: '1800001', name: 'GAURI SHANKAR SAIN', department: 'Maintenance', designation: 'Executive', role: 'EMPLOYEE', password: 'Gauri_01' },
  { empCode: '1800127', name: 'GEETA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Geeta_27' },
  { empCode: '1801761', name: 'GIRRAJ VERMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Girraj_61' },
  { empCode: '1801132', name: 'Gopal Singh', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Gopal_32' },
  { empCode: '1801274', name: 'GOPAL SINGH', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Gopal_74' },
  { empCode: '1802295', name: 'GOVIND SAIN', department: 'Production', designation: 'Helper - Production', role: 'EMPLOYEE', password: 'Govind_95' },
  { empCode: '1801926', name: 'GYAN KANWAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Gyan_26' },
  { empCode: '1801213', name: 'GYARSHI LAL MORYA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Gyarshi_13' },
  { empCode: '1801758', name: 'HANSRAJ MEENA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Hansraj_58' },
  { empCode: '1802320', name: 'HANSRAJ MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Hansraj_20' },
  { empCode: '1802344', name: 'HANSRAJ YOGI', department: 'Security', designation: 'Supervisor', role: 'SUPERVISOR', password: 'Hansraj_44' },
  { empCode: '1800258', name: 'HANUMAN CHAUDHRAY', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Hanuman_58' },
  { empCode: '1802340', name: 'HANUMAN NARUKA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Hanuman_40' },
  { empCode: '1802354', name: 'HARESH KUMAR KANSAL', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Haresh_54' },
  { empCode: '1802064', name: 'HARPHOOL MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Harphool_64' },
  { empCode: '1801215', name: 'HEERA LAL', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Heera_15' },
  { empCode: '1802296', name: 'HEERA NAND MAURYA', department: 'Production', designation: 'Helper - Production', role: 'EMPLOYEE', password: 'Heera_96' },
  { empCode: '1802314', name: 'HIMANSHU CHOPRA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Himanshu_14' },
  { empCode: '1801279', name: 'HUKAM CHAND JANGID', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Hukam_79' },
  { empCode: '1802029', name: 'JAGADISH NARAYAN MEENA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Jagadish_29' },
  { empCode: '1801105', name: 'Jagdish Prasad Meena', department: 'Production', designation: 'Executive', role: 'EMPLOYEE', password: 'Jagdish_05' },
  { empCode: '1802153', name: 'JAGRAM MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Jagram_53' },
  { empCode: '1800056', name: 'JANSHI RAM MEENA', department: 'Production', designation: 'COOK', role: 'EMPLOYEE', password: 'Janshi_56' },
  { empCode: '1802179', name: 'JASWANT SINGH TOMER', department: 'Administration', designation: 'Office Boy', role: 'EMPLOYEE', password: 'Jaswant_79' },
  { empCode: '1802370', name: 'JAYSINGH', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Jaysingh_70' },
  { empCode: '1801037', name: 'Jitendra kumar Parashar', department: 'Administration', designation: 'Executive', role: 'EMPLOYEE', password: 'Jitendra_37' },
  { empCode: '1801219', name: 'JITENDRA RAIGAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Jitendra_19' },
  { empCode: '1802350', name: 'JITENDRA SINGH', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Jitendra_50' },
  { empCode: '1801406', name: 'Jitendra Singh Gurjar', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Jitendra_06' },
  { empCode: '1801220', name: 'JYANTI PRASAD SHARMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Jyanti_20' },
  { empCode: '1801221', name: 'KAILASH CHAND', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kailash_21' },
  { empCode: '1801872', name: 'KAILASH CHAND', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kailash_72' },
  { empCode: '1800169', name: 'KAILASHI DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kailashi_69' },
  { empCode: '1801781', name: 'KALU RAM RAIGAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kalu_81' },
  { empCode: '1801167', name: 'Kamal Kishore Sharma', department: 'Production', designation: 'Vessel Washing', role: 'EMPLOYEE', password: 'Kamal_67' },
  { empCode: '1802381', name: 'KAMAL KUMAR BAIRWA', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Kamal_81' },
  { empCode: '1801658', name: 'Kamal Singh', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kamal_58' },
  { empCode: '1801896', name: 'KAMAL SINGH MAWARI', department: 'Human Resources', designation: 'Executive', role: 'EMPLOYEE', password: 'Kamal_96' },
  { empCode: '1801368', name: 'Kamlesh Bunkar', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kamlesh_68' },
  { empCode: '1801776', name: 'KAMLESH DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kamlesh_76' },
  { empCode: '1801662', name: 'KAMLESH KUMAR SHARMA', department: 'Operations', designation: 'Executive', role: 'EMPLOYEE', password: 'Kamlesh_62' },
  { empCode: '1801742', name: 'KAN SINGH', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Kan_42' },
  { empCode: '1802279', name: 'KANA RAM MEENA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Kana_79' },
  { empCode: '1802135', name: 'KANA RAM YOGI', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Kana_35' },
  { empCode: '1802258', name: 'KAPIL MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kapil_58' },
  { empCode: '1802333', name: 'KARAN NARUKA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Karan_33' },
  { empCode: '1801745', name: 'KAVITA BALAI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kavita_45' },
  { empCode: '1802159', name: 'KAVITA SISODIYA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kavita_59' },
  { empCode: '1802334', name: 'KHEMRAJ MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Khemraj_34' },
  { empCode: '1802192', name: 'KIRAN DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kiran_92' },
  { empCode: '1801225', name: 'KULDEEP SINGH RAJAWAT', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kuldeep_25' },
  { empCode: '1801226', name: 'KULDEEP VERMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Kuldeep_26' },
  { empCode: '1801227', name: 'LAL CHAND MORIYA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Lal_27' },
  { empCode: '1800094', name: 'LALA RAM MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Lala_94' },
  { empCode: '1802374', name: 'LALIT MUNDRA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Lalit_74' },
  { empCode: '1801321', name: 'Lavleen Gurjar', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Lavleen_21' },
  { empCode: '1802142', name: 'LAXMI KANWAR RAJAWAT', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Laxmi_42' },
  { empCode: '1802337', name: 'LOKESH KUMAR MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Lokesh_37' },
  { empCode: '1802249', name: 'MADAN SINGH', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Madan_49' },
  { empCode: '1801129', name: 'Maharaj Singh Gurjar', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Maharaj_29' },
  { empCode: '1801171', name: 'Mahendra Singh Boran', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Mahendra_71' },
  { empCode: '1800250', name: 'MAHENDRA YADAV', department: 'Procurement', designation: 'Officer', role: 'EMPLOYEE', password: 'Mahendra_50' },
  { empCode: '1801416', name: 'Malu Ram', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Malu_16' },
  { empCode: '1801361', name: 'Mamraj Raiger', department: 'Production', designation: 'Supervisior - Production', role: 'SUPERVISOR', password: 'Mamraj_61' },
  { empCode: '1802006', name: 'MAMTA', department: 'Production', designation: 'Helper-Production', role: 'EMPLOYEE', password: 'Mamta_06' },
  { empCode: '1801363', name: 'Mamta Devi', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Mamta_63' },
  { empCode: '1802232', name: 'MAMTA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Mamta_32' },
  { empCode: '1802222', name: 'MANISH KUMAR BAIRWA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Manish_22' },
  { empCode: '1801130', name: 'Manish Kumar Jaiman', department: 'Security', designation: 'Officer', role: 'EMPLOYEE', password: 'Manish_30' },
  { empCode: '1802299', name: 'MANJU', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Manju_99' },
  { empCode: '1800133', name: 'MANJU DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Manju_33' },
  { empCode: '1800106', name: 'MANJU DEVI MORYA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Manju_06' },
  { empCode: '1800029', name: 'MANOJ KUMAR JAIN', department: 'Procurement', designation: 'Senior Officer', role: 'EMPLOYEE', password: 'Manoj_29' },
  { empCode: '1802217', name: 'MANOJ KUMAR MEENA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Manoj_17' },
  { empCode: '1801587', name: 'MANPHOLI DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Manpholi_87' },
  { empCode: '1802385', name: 'MANSHA RAM', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Mansha_85' },
  { empCode: '1801986', name: 'MANSINGH MEENA', department: 'Maintenance', designation: 'Electrician', role: 'EMPLOYEE', password: 'Mansingh_86' },
  { empCode: '1800221', name: 'MAYA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Maya_21' },
  { empCode: '1800282', name: 'MEENA MISHRA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Meena_82' },
  { empCode: '1800171', name: 'MEERA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Meera_71' },
  { empCode: '1800989', name: 'MEERA DEVI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Meera_89' },
  { empCode: '1802378', name: 'MEHUL KUMAR SONI', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Mehul_78' },
  { empCode: '1801232', name: 'MOHAR SINGH GURJAR', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Mohar_32' },
  { empCode: '1802361', name: 'MOHIT VERMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Mohit_61' },
  { empCode: '1802284', name: 'MONU VERMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Monu_84' },
  { empCode: '1801180', name: 'Mukesh', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Mukesh_80' },
  { empCode: '1801919', name: 'MUKESH JANGID', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Mukesh_19' },
  { empCode: '1802114', name: 'MUKESH KUMAR MALI', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Mukesh_14' },
  { empCode: '1801284', name: 'MUKESH KUMAR MEENA', department: 'Distribution', designation: 'Driver', role: 'EMPLOYEE', password: 'Mukesh_84' },
  { empCode: '1801841', name: 'MUKESH KUMAR YADAV', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Mukesh_41' },
  { empCode: '1800347', name: 'MUKESH SHARMA', department: 'Procurement', designation: 'Officer', role: 'EMPLOYEE', password: 'Mukesh_47' },
  { empCode: '1801425', name: 'Mukesh Sharma', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Mukesh_25' },
  { empCode: '1801198', name: 'Mukesh Verma', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Mukesh_98' },
  { empCode: '1802253', name: 'MUKUT BIHARI SHARMA', department: 'Production', designation: 'Helper', role: 'EMPLOYEE', password: 'Mukut_53' },
  { empCode: '1802093', name: 'NAGENDRA JATAV', department: 'Security', designation: 'Security', role: 'EMPLOYEE', password: 'Nagendra_93' },
  { empCode: '1800059', name: 'NAND KISHOR JAT', department: 'Administration', designation: 'Office Boy', role: 'EMPLOYEE', password: 'Nand_59' },
];
